name: Easy-VDL
package: community.lazycat.app.easy-vdl
version: 0.1.0
description: 统一视频下载平台
homepage: https://hub.docker.com/r/qq918652593/easy-vdl
author: 隔壁小王
application:
    subdomain: easy-vdl
    multi_instance: true
    background_task: true
    public_path:
        - /
    routes:
        - /=http://easy-vdl:80
services:
    easy-vdl:
        # qq918652593/easy-vdl:latest
        image: registry.lazycat.cloud/czyt/qq918652593/easy-vdl:9251cf2b0e51a322
        binds:
            - /lzcapp/run/mnt/home/下载:/app/downloads
ext_config:
    enable_document_access: true
    enable_media_access: true
